Updated to work with GTNH 2.5.0, bumped version, updated dependencies…
GTNewHorizons/nesql-exporter pull request #2
Opened 2024-01-30 21:16 UTC by Makonew-Dev

…, fixed com.github.dcysteine.nesql.exporter.plugin.gregtech.util.RecipeMap to work with GT5 after refactor of Recipe maps

2024-03-12 13:34 UTC, boubou19 requested changes

2024-03-12 13:34 UTC, boubou19 commented on src/main/java/com/github/dcysteine/nesql/sql/quest/QuestLine.java
> -import jakarta.persistence.Column;
no star imports, please configure your IDE to avoid this.

2024-03-12 13:34 UTC, boubou19 commented
@Makonew-Dev please address the review and this will be merged.

2024-04-28 10:33 UTC, Dream-Master commented
@Makonew-Dev any news

2024-04-28 10:46 UTC, D-Cysteine commented
Sorry for the long delay on this. I've been working on updating the exporter to work with the latest version of the pack, so this PR should no longer be needed once I've finished that.

2024-04-28 10:46 UTC, closed without merging

2024-04-28 10:48 UTC, Dream-Master commented
@D-Cysteine we releasing 2.6.0 today soone more bump :)